# Generated by Django 5.2.11 on 2026-02-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_parseddocument_is_premium_parseddocument_price'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unlockedcontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchase',
            name='parsed_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.parseddocument'),
        ),
        migrations.AddField(
            model_name='unlockedcontent',
            name='parsed_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.parseddocument'),
        ),
        migrations.AlterField(
            model_name='unlockedcontent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
