# Generated by Django 5.2.11 on 2026-02-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('products', '0003_alter_unlockedcontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='target_branch',
            field=models.ForeignKey(blank=True, help_text='Stored temporarily for assigning Gold Pass', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.branch'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='target_semester',
            field=models.ForeignKey(blank=True, help_text='Stored temporarily for assigning Gold Pass', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester'),
        ),
    ]
