# Generated by Django 5.2.11 on 2026-02-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_purchase_target_branch_purchase_target_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='target_branch',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='target_semester',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_crash_course',
            field=models.BooleanField(default=True, help_text='Unlocks crash courses'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_formula',
            field=models.BooleanField(default=True, help_text='Unlocks formula sheets'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_important_q',
            field=models.BooleanField(default=True, help_text='Unlocks important questions'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_notes',
            field=models.BooleanField(default=True, help_text='Unlocks structured notes'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_pyq',
            field=models.BooleanField(default=True, help_text='Unlocks solved PYQs'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_short_notes',
            field=models.BooleanField(default=True, help_text='Unlocks short notes'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_unsolved_pyq',
            field=models.BooleanField(default=True, help_text='Unlocks unsolved PYQs'),
        ),
    ]
