# Generated by Django 5.2.11 on 2026-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_purchase_target_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. TEST100 or SAVE50', max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Between 1 and 100')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
