# Generated by Django 5.2.11 on 2026-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='List of topics for this unit, synced from syllabus.'),
        ),
    ]
