# Generated by Django 5.2.11 on 2026-03-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('predictability_score', models.FloatField(default=0.0, help_text='0.0 to 100.0, e.g., 78.5%')),
                ('total_papers_analyzed', models.PositiveIntegerField(default=0, help_text='How many PYQs were used to generate this data.')),
                ('unit_roi_data', models.JSONField(blank=True, default=dict, help_text="Format: { '1': {'avg_marks': 14, 'efficiency': 'High', 'name': '...'} }")),
                ('syllabus_heatmap', models.JSONField(blank=True, default=dict, help_text="Format: { 'Topic Name': {'frequency': 4, 'years': [2019, 2021, 2022, 2023], 'unit': 1} }")),
                ('complexity_breakdown', models.JSONField(blank=True, default=dict, help_text="Format: { 'Theory': 45, 'Numerical': 30, 'Derivation': 25 }")),
                ('top_repeated_questions', models.JSONField(blank=True, default=list, help_text="Array of objects: [{'text': '...', 'occurrences': 5, 'years': [2021, 2023]}]")),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='academics.subject')),
            ],
            options={
                'verbose_name_plural': 'Subject Analytics',
            },
        ),
    ]
