# Generated by Django 5.2.11 on 2026-03-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_unit_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
