# Generated by Django 5.2.11 on 2026-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_branch_code_alter_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='e.g., CSE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='e.g., CS-402', max_length=100),
        ),
    ]
