# Generated by Django 5.2.11 on 2026-02-23 10:36

import apps.content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SYLLABUS', 'Official Syllabus'), ('PYQ', 'Solved Previous Year Question Paper'), ('UNSOLVED_PYQ', 'Unsolved PYQ Paper'), ('NOTES', 'Notes'), ('SHORT_NOTES', 'Quick Revision Short Notes'), ('IMPORTANT_Q', 'Important Questions'), ('FORMULA', 'Formula Sheet'), ('CRASH_COURSE', 'Video Crash Course Links')], max_length=20)),
                ('title', models.CharField(help_text="e.g., '2023 OS Main Exam'", max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='For PYQs', null=True)),
                ('system_prompt', models.TextField(default=apps.content.models.default_system_prompt, help_text='The core instruction given to the AI. You can edit this directly per-document to steer the LLM.')),
                ('source_file', models.FileField(blank=True, help_text='Upload raw PDF or Image for AI Parsing', null=True, upload_to='raw_docs/')),
                ('source_text', models.TextField(blank=True, help_text="OR paste raw text manually here if you don't have a file.", null=True)),
                ('parsing_status', models.CharField(choices=[('PENDING', 'Pending AI Parsing'), ('PROCESSING', 'Processing in Background'), ('COMPLETED', 'Successfully Parsed'), ('FAILED', 'Parsing Failed')], default='PENDING', help_text='Current state of the AI Parser', max_length=20)),
                ('parsing_completed_chunks', models.PositiveIntegerField(default=0, help_text='Number of chunks processed so far')),
                ('parsing_total_chunks', models.PositiveIntegerField(default=0, help_text='Total number of chunks to process')),
                ('recreation_completed_images', models.PositiveIntegerField(default=0, help_text='Number of images recreated so far')),
                ('recreation_total_images', models.PositiveIntegerField(default=0, help_text='Total number of images to recreate')),
                ('structured_data', models.JSONField(blank=True, help_text='Stores the exact LangChain parsed output. Auto-filled by AI.', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('render_mode', models.CharField(choices=[('NATIVE', 'Native AI Generated Render (JSON/Markdown)'), ('DIRECT_PDF', 'Direct PDF Render (Raw File Viewer)')], default='NATIVE', help_text='Choose how this document should be displayed to the user.', max_length=20)),
                ('is_premium', models.BooleanField(default=False, help_text='Check if this content requires a premium subscription or one-time purchase.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Set a specific price to unlock just this document.', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(help_text="Select all branch/semester variants this document applies to. E.g. attach to AD's Physics, CSE's Physics, etc.", related_name='parsed_documents', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a screenshot or page scan', upload_to='raw_docs/images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the AI should read this image (0, 1, 2...)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.parseddocument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
