# Generated by Django 5.2.11 on 2026-03-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='latex_validated',
            field=models.BooleanField(default=False, help_text="Whether this document's LaTeX has been validated and fixed by the KaTeX pipeline."),
        ),
    ]
