# Generated by Django 5.2.11 on 2026-02-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PYQ', 'Previous Year Question Paper'), ('NOTES', 'Chapter Notes'), ('FORMULA', 'Formula Sheet')], max_length=20)),
                ('title', models.CharField(help_text="e.g., '2023 OS Main Exam'", max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='For PYQs', null=True)),
                ('structured_data', models.JSONField(help_text='Stores the exact LangChain parsed output.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_documents', to='academics.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
