# Generated by Django 5.2.11 on 2026-02-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_parseddocument_delete_studymaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddocument',
            name='document_type',
            field=models.CharField(choices=[('SYLLABUS', 'Official Syllabus'), ('PYQ', 'Previous Year Question Paper'), ('NOTES', 'Comprehensive Notes'), ('SHORT_NOTES', 'Quick Revision Short Notes'), ('IMPORTANT_Q', 'Important Questions'), ('FORMULA', 'Formula Sheet'), ('CRASH_COURSE', 'Video Crash Course Links')], max_length=20),
        ),
    ]
