# Generated by Django 5.2.11 on 2026-02-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_parseddocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='parsing_status',
            field=models.CharField(choices=[('PENDING', 'Pending AI Parsing'), ('PROCESSING', 'Processing in Background'), ('COMPLETED', 'Successfully Parsed'), ('FAILED', 'Parsing Failed')], default='PENDING', help_text='Current state of the AI Parser', max_length=20),
        ),
        migrations.AddField(
            model_name='parseddocument',
            name='source_file',
            field=models.FileField(blank=True, help_text='Upload raw PDF or Image for AI Parsing', null=True, upload_to='raw_docs/'),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Stores the exact LangChain parsed output. Auto-filled by AI.', null=True),
        ),
    ]
