# Generated by Django 5.2.11 on 2026-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_parseddocument_parsing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='source_text',
            field=models.TextField(blank=True, help_text="OR paste raw text manually here if you don't have a file.", null=True),
        ),
    ]
