# Generated by Django 5.2.11 on 2026-02-20 16:55

import apps.content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_parseddocument_source_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='system_prompt',
            field=models.TextField(default=apps.content.models.default_system_prompt, help_text='The core instruction given to the AI. You can edit this directly per-document to steer the LLM.'),
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a screenshot or page scan', upload_to='raw_docs/images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the AI should read this image (0, 1, 2...)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.parseddocument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
