# Generated by Django 5.2.11 on 2026-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_parseddocument_system_prompt_documentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Check if this content requires a premium subscription or one-time purchase.'),
        ),
        migrations.AddField(
            model_name='parseddocument',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Set a specific price to unlock just this document.', max_digits=8, null=True),
        ),
    ]
