# Generated by Django 5.2.11 on 2026-02-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_parseddocument_is_premium_parseddocument_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddocument',
            name='document_type',
            field=models.CharField(choices=[('SYLLABUS', 'Official Syllabus'), ('PYQ', 'Solved Previous Year Question Paper'), ('UNSOLVED_PYQ', 'Unsolved PYQ Paper'), ('NOTES', 'Comprehensive Notes'), ('SHORT_NOTES', 'Quick Revision Short Notes'), ('IMPORTANT_Q', 'Important Questions'), ('FORMULA', 'Formula Sheet'), ('CRASH_COURSE', 'Video Crash Course Links')], max_length=20),
        ),
    ]
