# Generated by Django 5.2.11 on 2026-02-20 19:25

from django.db import migrations, models


def copy_subjects(apps, schema_editor):
    ParsedDocument = apps.get_model('content', 'ParsedDocument')
    for doc in ParsedDocument.objects.all():
        if doc.subject_id:
            doc.subjects.add(doc.subject)

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('content', '0008_alter_parseddocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='subjects',
            field=models.ManyToManyField(help_text="Select all branch/semester variants this document applies to. E.g. attach to AD's Physics, CSE's Physics, etc.", related_name='parsed_documents', to='academics.subject'),
        ),
        migrations.RunPython(copy_subjects),
        migrations.RemoveField(
            model_name='parseddocument',
            name='subject',
        ),
    ]
