# Generated by Django 5.2.11 on 2026-02-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_parseddocument_subject_and_more'),
    ]

    operations = [
    ]
