# Generated by Django 5.2.11 on 2026-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_copy_subjects_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='parsing_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentage of document parsed (0-100)'),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='document_type',
            field=models.CharField(choices=[('SYLLABUS', 'Official Syllabus'), ('PYQ', 'Solved Previous Year Question Paper'), ('UNSOLVED_PYQ', 'Unsolved PYQ Paper'), ('NOTES', 'Notes'), ('SHORT_NOTES', 'Quick Revision Short Notes'), ('IMPORTANT_Q', 'Important Questions'), ('FORMULA', 'Formula Sheet'), ('CRASH_COURSE', 'Video Crash Course Links')], max_length=20),
        ),
    ]
