# Generated by Django 5.2.11 on 2026-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_parseddocument_parsing_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='parsing_completed_chunks',
            field=models.PositiveIntegerField(default=0, help_text='Number of chunks processed so far'),
        ),
        migrations.AddField(
            model_name='parseddocument',
            name='parsing_total_chunks',
            field=models.PositiveIntegerField(default=0, help_text='Total number of chunks to process'),
        ),
    ]
