# Generated by Django 5.2.11 on 2026-02-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_parseddocument_parsing_completed_chunks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseddocument',
            name='parsing_progress',
        ),
    ]
