# Generated by Django 5.2.11 on 2026-02-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_remove_parseddocument_parsing_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='recreation_completed_images',
            field=models.PositiveIntegerField(default=0, help_text='Number of images recreated so far'),
        ),
        migrations.AddField(
            model_name='parseddocument',
            name='recreation_total_images',
            field=models.PositiveIntegerField(default=0, help_text='Total number of images to recreate'),
        ),
    ]
