# Generated by Django 5.2.11 on 2026-02-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_parseddocument_recreation_completed_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='render_mode',
            field=models.CharField(choices=[('NATIVE', 'Native AI Generated Render (JSON/Markdown)'), ('DIRECT_PDF', 'Direct PDF Render (Raw File Viewer)')], default='NATIVE', help_text='Choose how this document should be displayed to the user.', max_length=20),
        ),
    ]
