# Generated by Django 5.2.11 on 2026-02-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_parseddocument_render_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='is_sliced',
            field=models.BooleanField(default=False, help_text='Checked if this document is processed via Sliced Secure PDF (SSP)'),
        ),
        migrations.AddField(
            model_name='parseddocument',
            name='secure_key',
            field=models.BinaryField(blank=True, help_text='AES key for chunk decryption (Server-side storage)', null=True),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='Page number (1-indexed)')),
                ('encrypted_file', models.FileField(help_text='Encrypted page blob', upload_to='secure_chunks/')),
                ('iv', models.BinaryField(help_text='AES GCM initialization vector')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content.parseddocument')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
