# Generated by Django 5.2.11 on 2026-02-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_mcqquiz_mcqquestion_quizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquiz',
            name='related_document',
        ),
        migrations.RemoveField(
            model_name='mcqquiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='MCQQuestion',
        ),
        migrations.DeleteModel(
            name='MCQQuiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
