# Generated by Django 5.2.11 on 2026-02-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice (MCQ)'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('FILL', 'Fill in the Blank'), ('TF', 'True / False')], default='MCQ', max_length=10)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('body_md', models.TextField(help_text='Question text in Markdown. Use $...$ for inline LaTeX, $$...$$ for block.')),
                ('option_a', models.TextField(blank=True)),
                ('option_b', models.TextField(blank=True)),
                ('option_c', models.TextField(blank=True)),
                ('option_d', models.TextField(blank=True)),
                ('correct_answer', models.TextField(help_text='MCQ: A/B/C/D | TF: True/False | FILL: exact phrase | SHORT/LONG: model answer (Markdown)')),
                ('explanation_md', models.TextField(blank=True, help_text='Step-by-step explanation shown after attempt. Markdown + LaTeX.')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to='academics.subject')),
                ('unit', models.ForeignKey(blank=True, help_text='Leave blank = whole subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_questions', to='academics.unit')),
            ],
            options={
                'ordering': ['subject', 'unit', 'difficulty', 'question_type'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='sets', to='practice.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='academics.subject')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_sets', to='academics.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.questionset')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
