# Generated by Django 5.2.11 on 2026-02-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold_pass_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_pass_users', to='academics.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='gold_pass_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_pass_users', to='academics.semester'),
        ),
    ]
