# Generated by Django 5.2.11 on 2026-02-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_purchase_target_branch_and_more'),
        ('users', '0002_user_gold_pass_branch_user_gold_pass_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_users', to='products.subscriptionplan'),
        ),
    ]
