# Generated by Django 5.2.11 on 2026-02-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_active_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
