"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import json
from pathlib import Path
import urllib.parse as urlparse
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env_path = BASE_DIR / '.env'
loaded = load_dotenv(env_path, override=True)
if not loaded:
    print(f"Warning: .env file NOT loaded from {env_path}")
else:
    print(f".env file loaded successfully from {env_path}")
    # Verify if DATABASE_URL is in the environment
    if 'DATABASE_URL' in os.environ:
        print("DATABASE_URL found in environment.")
    else:
        print("DATABASE_URL NOT found in environment even after loading .env.")

# Add apps/ directory to Python path
sys.path.insert(0, str(BASE_DIR / 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dummy-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'
PRODUCTION = not DEBUG


def _env_bool(name: str, default: bool) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://campusprep.in'
]

# Reverse proxy / HTTPS settings
# Required when TLS terminates at a load balancer/CDN (for example Cloudflare/Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', PRODUCTION)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', PRODUCTION)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', PRODUCTION)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Local Apps
    'apps.common.apps.CommonConfig',
    'apps.users.apps.UsersConfig',
    'apps.academics.apps.AcademicsConfig',
    'apps.products.apps.ProductsConfig',
    'apps.content.apps.ContentConfig',
    'apps.gamification.apps.GamificationConfig',
    'apps.practice.apps.PracticeConfig',
    'apps.notifications.apps.NotificationsConfig',
    'webpush',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.users.context_processors.turnstile',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Parse DATABASE_URL manually
db_url = os.getenv('DATABASE_URL')

if db_url and (db_url.startswith('postgresql://') or db_url.startswith('postgres://')):
    url = urlparse.urlparse(db_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path[1:],
            'USER': url.username,
            'PASSWORD': url.password,
            'HOST': url.hostname,
            'PORT': url.port,
        }
    }
elif db_url and db_url.startswith('sqlite://'):
    # Support for sqlite:///data/db.sqlite3
    url = urlparse.urlparse(db_url)
    db_path = url.path.lstrip('/')
    
    # If the path starts with 'app/', strip it since app is BASE_DIR in docker
    if db_path.startswith('app/'):
        db_path = db_path[4:]
        
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / db_path,
        }
    }
else:
    if DEBUG:
        print(f"Warning: DATABASE_URL not set or invalid ({db_url}). Using default SQLite.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Storage Settings (Backblaze B2 S3)
if not DEBUG or os.getenv('USE_S3', 'False') == 'True':
    AWS_ACCESS_KEY_ID = os.getenv('B2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('B2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('B2_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('B2_REGION')
    AWS_S3_ENDPOINT_URL = os.getenv('B2_ENDPOINT')
    
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_QUERYSTRING_AUTH = True
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

WHITENOISE_MANIFEST_STRICT = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site ID (required by allauth)
SITE_ID = 1

# Auth Settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ── Email ──────────────────────────────────────────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ── Google OAuth ───────────────────────────────────────────────────────────
_google_raw = os.getenv('GOOGLE_CLIENT_JSON', '{}')
try:
    _google_data = json.loads(_google_raw).get('web', {})
    GOOGLE_CLIENT_ID = _google_data.get('client_id', '')
    GOOGLE_CLIENT_SECRET = _google_data.get('client_secret', '')
except Exception:
    GOOGLE_CLIENT_ID = ''
    GOOGLE_CLIENT_SECRET = ''

# ── Allauth ────────────────────────────────────────────────────────────────
ACCOUNT_ADAPTER = 'apps.users.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'apps.users.adapters.SocialAccountAdapter'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_SIGNUP_REDIRECT_URL = '/onboarding/'
ACCOUNT_LOGIN_REDIRECT_URL = '/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if PRODUCTION else 'http'

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True
# If Google email matches an existing account → auto-connect, no form
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Razorpay Settings
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')
# AI Parser Settings
AI_PARSER_RETRIES = int(os.getenv('AI_PARSER_RETRIES', '10'))
AI_PARSER_CHUNK_SIZE = int(os.getenv('AI_PARSER_CHUNK_SIZE', '5'))
AI_PARSER_MAX_CONCURRENCY = int(os.getenv('AI_PARSER_MAX_CONCURRENCY', '5'))
AI_PARSER_OVERLAP_SIZE = int(os.getenv('AI_PARSER_OVERLAP_SIZE', '1'))

# Model Mappings for AI Parser
AI_PARSER_DEFAULT_MODEL = os.getenv('AI_PARSER_DEFAULT_MODEL', 'gemini/gemini-2.5-flash')
AI_PARSER_MODEL_MAPPING = {
    'SYLLABUS': os.getenv('AI_PARSER_SYLLABUS_MODEL', AI_PARSER_DEFAULT_MODEL),
    'PYQ': os.getenv('AI_PARSER_PYQ_MODEL', AI_PARSER_DEFAULT_MODEL),  # Use heavier model for PYQs if needed
    'UNSOLVED_PYQ': os.getenv('AI_PARSER_PYQ_MODEL', AI_PARSER_DEFAULT_MODEL),
    'NOTES': os.getenv('AI_PARSER_NOTES_MODEL', AI_PARSER_DEFAULT_MODEL),
    'SHORT_NOTES': os.getenv('AI_PARSER_NOTES_MODEL', AI_PARSER_DEFAULT_MODEL),
    'IMPORTANT_Q': os.getenv('AI_PARSER_IMPORTANT_Q_MODEL', AI_PARSER_DEFAULT_MODEL),
    'FORMULA': os.getenv('AI_PARSER_FORMULA_MODEL', AI_PARSER_DEFAULT_MODEL),
}

# Celery Settings
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Caching Settings (Valkey)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv('CACHE_URL', 'redis://127.0.0.1:6379/1'),
    }
}

# X-Frame-Options to allow framing PDFs natively
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Cloudflare Turnstile Settings
CLOUDFLARE_TURNSTILE_SITE_KEY = os.getenv('CLOUDFLARE_TURNSTILE_SITE_KEY', '')
CLOUDFLARE_TURNSTILE_SECRET_KEY = os.getenv('CLOUDFLARE_TURNSTILE_SECRET_KEY', '')
TURNSTILE_ENABLED = bool(CLOUDFLARE_TURNSTILE_SITE_KEY and CLOUDFLARE_TURNSTILE_SECRET_KEY)

# Web Push Settings
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BJRuhh12FavXvn8HXPjpUlS66aEuBaMUViZB9dnRP7dpGbdLukdLNK5M1F-yPkcGeLyCZvBY3Y9ZQp1LUH3vzJM",
    "VAPID_PRIVATE_KEY": "EkZX7mVKA5060KUK6Rj0fkOntfmaPMnrGwftazT0VHE",
    "VAPID_ADMIN_EMAIL": "admin@rgpv.live"
}
