# Generated by Django 5.2.11 on 2026-03-03 18:57

import apps.student_notes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.JSONField(default=apps.student_notes.models.default_blocks, help_text='Structured JSON block document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='academics.subject')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='academics.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unit__number'],
                'unique_together': {('user', 'subject', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='student_notes.note')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Base Notes', max_length=255)),
                ('blocks', models.JSONField(default=apps.student_notes.models.default_blocks, help_text='Admin-authored block content')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_notes', to='academics.subject')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_notes', to='academics.unit')),
            ],
            options={
                'ordering': ['unit__number'],
                'unique_together': {('subject', 'unit')},
            },
        ),
    ]
